---
title: "MOC Usage Report"
output:
  pdf_document:
    includes:
      in_header: header.tex
  df_print: kable
  html_document:
    df_print: paged
mainfont: Roboto Light
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

\vspace{42pt}

<!-- Set variables -->
<!-- institution_n : name of the institution, should reflect same as the one in the database. -->
<!-- projects: should be a csv list of the projects for which the report is required or could be 'all' if the required report is for all the projects in the particular institution. -->

```{r, echo=FALSE, warning=FALSE, max.print=1}
institution_n = "Northeastern University" 
projects_in_rpt = "all"
# if only certain number of projects needs to be in the report comment the above and uncomment below and enter the name of projects in the same format as project 1 and project 2 is written. replace project 1 and project 2 as well with the valid projects.
#  projects_in_rpt ='"project_name"
# "project 1"
# "project 2"'

# set the base path where all the csv exist and where the output of the pdf report will be generated.
base_path="~/MS/CS6640/R"
csv_path="./csv/"
# This expects that all the csv files have the same name.
csv_file_name="2019_10_02.csv"
project_path = paste0(csv_path,"project/",csv_file_name)
item_path = paste0(csv_path,"item/",csv_file_name)
item_type_path = paste0(csv_path,"item_type/",csv_file_name)
item_ts_path = paste0(csv_path,"item_ts/",csv_file_name)
institution_path = paste0(csv_path,"institution/",csv_file_name)
institution2project_path = paste0(csv_path,"institution2project/",csv_file_name)
```

## Institution: `r institution_n`


\vspace{48pt}
<!-- Print details of the institution on the PDF  -->
## Institution Details:
__Name:__ `r institution_n`
\newline __Address:__ 360 Huntington Ave, Boston, MA 02115
\newline __Phone:__ (617) 373-2000
\newline __email:__ mocuser@northeastern.neu.edu


```{r, echo=FALSE, warning=FALSE, max.print=1, results='asis' }
# load library
library(pacman)
pacman::p_load(pacman, dplyr, ggplot2, rio, gridExtra, scales, ggcorrplot, caret, e1071,lubridate,knitr, kableExtra,hflights,forcats, crayon)

setwd(base_path)

# load all csv files from the path provided in the variables and replace all implicit NA with explicit NA.
project <- read.csv (project_path, na.strings = "N/A")
item_type <- read.csv (item_type_path, na.strings = "N/A")
item <- read.csv (item_path, na.strings = "N/A")
item_ts <- read.csv(item_ts_path, na.strings = "N/A")
institution <- read.csv(institution_path, na.strings = "N/A")
institution2project <- read.csv(institution2project_path, na.strings = "N/A")

# create tables for further agregating data and generating report
result_proj_inst <- left_join(project,institution2project, by = "project_id")
result_proj_inst <- left_join(result_proj_inst,institution, by = "institution_id")
proj2inst <- result_proj_inst %>% filter(institution_name == institution_n) %>% select(project_name)
result <- right_join(item_type,item, by = "item_type_id")
result2 <- right_join(result_proj_inst,result, by = "project_id")

# item_ts_minmax needs to be populated with summarized table rather than item_ts to improve the performance. This is the key peformance bottleneck. 
item_ts_minmax <- select(item_ts,item_id,start_ts) %>% group_by(item_id) %>% summarise(max_ts = max(as.POSIXct(start_ts)), min_ts = min(as.POSIXct(start_ts)))

#item_ts_minmax <- read.csv ("./item_ts_minmax.csv", na.strings = "N/A")

item_usage <- select(item_ts_minmax,item_id,max_ts,min_ts) %>% group_by(item_id) %>% summarise( usage = difftime(max_ts,min_ts,units = "hours"))


# create final table which will be used to create the report. multiple read-write is present beacuse of the issue with implicit and explicit NA.
final_table <- select(right_join(item_usage,result2, by = "item_id"),institution_name, project_name,item_name, item_definition, usage) %>% mutate(usage = coalesce(usage, 0)) %>%  mutate_all(na_if,"") %>% mutate_if(is.factor,fct_explicit_na,na_level = "NA")
write.csv(final_table, file = "final_table.csv")
final_table <- read.csv ("./final_table.csv", na.strings = "N/A")

#final_table = final_table%>% mutate_if(is.factor,fct_explicit_na,na_level = "(Missing)")

if (projects_in_rpt == "all") {
active_proj_in_inst <- final_table %>% filter(institution_name == institution_n) %>% select(project_name)
active_proj_in_inst <- unique(active_proj_in_inst)
} else {
  active_proj_in_inst <- read.csv(text = projects_in_rpt)
}

for(i in 1:nrow(active_proj_in_inst)) {
  proj_n <- as.character(active_proj_in_inst[i,"project_name"])


  cat("\n\n\\pagebreak\n")
  
  
cat(paste("# Project: ", proj_n,""),'\n \n')
cat("___")
cat('\\newline \n')
cat('\\newline \n')
cat('\\newline \n')

print(
kable(final_table %>% filter(project_name == proj_n) %>% select(item_definition, usage) %>% group_by(item_definition) %>% summarise(count = n(), usage_hours = sum(usage)), caption="Project Usage Summary", format = "latex", booktabs = T,longtable = T) %>% row_spec(0,bold=TRUE)%>% kable_styling( full_width=TRUE, font_size=13, latex_options =c("repeat_header")))

print(
kable(final_table %>% filter(project_name == proj_n) %>% group_by(item_definition) %>% mutate(Usage_hours = round(usage, 2)) %>% select( item_name, item_definition, Usage_hours) , caption="Project Detailed Usage", format = "latex", booktabs = T,longtable = T) %>% row_spec(0,bold=TRUE) %>% kable_styling( full_width=TRUE, font_size=13, latex_options =c("repeat_header")))

}
```
##### 